### ISSUE TITLE
So.. this is a virus, huh?

### ISSUE THREAD

**Issue by ghost** [u08614s/Image2Code#1]
![284317958_1139148463327172_4689283497113347304_n](https://user-images.githubusercontent.com/90534409/170835686-f8193db4-c609-4ce4-8174-a9651b4b64e1.jpg)

upon my friend checking it, it's flagged as malicious. Gonna de-compile to assembly elements to investigate further. In future releasing something like this, don't make it malicious

**Comment by ghost** [comment]
I'm willing to accept this might be a false positive given obfuscation or compilation methods via Python, which it seems that may be the case. But please take care as to not trigger Virus warnings, falsely or not.

**Comment by u08614s** [comment]
このツールは、画像をバイナリ化して指定されたアドレスに書き込まれるようにするだけですし、コンパイル方法もデフォルトのものを使っているので、ウイルスが検知されるのは本当に奇妙です。

**Comment by ghost** [comment]
EN: Yeah. I've since come to the conclusion that it's a false positive and this can be caused by several things such as the method of compilation.

For example as far as I can tell the application seems to be a Python script compiled into a Windows executable. Which works just fine. however it can often cause anti virus applications to detect it as a hidden script embedded within an existing executable.

I have no problem with the application at question. But I simply ask that you be more mindful of possibilities such as this. Taking steps such as acknowledging the problem and establishing credibility is a good first step.

JAP: これは誤検出であり、コンパイルの方法などいくつかの原因があることがわかりました。

例えば、私が見た限りでは、このアプリケーションはWindowsの実行ファイルにコンパイルされたPythonスクリプトのようです。しかし、アンチウィルスアプリケーションは、既存の実行ファイルに埋め込まれた隠しスクリプトとしてこれを検出することがよくあります。

私は、このアプリケーションに何の問題もありません。しかし、このような可能性があることをもっと意識していただきたいと思います。問題を認識し、信頼性を確立するなどの措置をとることは、良い最初のステップです。

**Comment by u08614s** [comment]
ok thanks
